### ISSUE TITLE
support RGBA tuples for glyph colors  

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#116]
it turns out that

> Color can be encoded as integer or as RGBA tuple.

https://github.com/googlei18n/fontmake/issues/247#issuecomment-279169487

Currently glyphsLib only supports integers for color. We should add support for tuples too.

**Comment by punchcutter** [comment]
Just ran into this with a Glyphs file that was originally converted from FontLab. All colors that were set in FontLab came in as RGBA tuples. So casting fails which means everything fails. @schriftgestalt Too bad the Glyphs format doesn't only store RGBA tuples because the integers are really just pointers to an RGBA value anyway. Seems a bit ugly to allow both integers and tuples to be stored in the file.

**Comment by schriftgestalt** [comment]
There is no proper way of converting fls or Robofont colors into the Glyphs color indexes. And people might like to store custom colors. On the other hand, custom colors might be stored in a custom parameter (public.color) like when imported from UFO. 
For now, 'color' can have both. I'll have a look at the parser.

**Comment by punchcutter** [comment]
@anthrotype This can be closed now, right?
