### ISSUE TITLE
glyphsLib treats some quoted values as numeric

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/glyphsLib#209]
The glyphsLib parsing/casting code treats some values as numeric although they are stored in (at least some versions of, e.g. appVersion 998) .glyphs files as quoted strings.  These are:

appVersion
panose values in list
weightClass value

Believing they are numeric, glyphsLib writes these values out without quotes.

This difference in representation means glyphsLib cannot read and then write files without modification.  When using glyphsLib to make bulk changes to .glyphs files, this leads to extraneous changes in the diffs.  Glyphs appears to read these values in ok when unquoted.

On the other hand, it seems like panose and weightClass (if not appVersion) are indeed numeric.  It seems consumers of the parsed data returned by glyphsLib should be able to continue to expect them to be numbers and not strings. So it's not clear glyphsLib is at fault here.

In addition, glyphsLib represents all character data in strings under 0x20 as octal escape sequences.  This causes tabs in strings to be converted to the sequence "\011".  Perhaps glyphsLib should make an exception for tab.

**Comment by anthrotype** [comment]
Let me summarise what I've understood so far from the discussion at https://github.com/googlei18n/noto-source/pull/85.

It would be great if Georg (@schriftgestalt) could find some spare time to comment on each of these points.

There seems to be two kinds of custom parameters: the built-in ones which are supported by Glyphs.app and whose type (whether string or numeric) is known, and arbitrary ones that are user-defined and, because their type is not known in advance, are implicitly treated as strings.

For example, `xHeight` is not one of the supported custom parameters; it's actually a public property of font masters, and the type is numeric (unquoted).

```
xHeight = 500;
```

The Noto fonts however sometimes store `xHeight` as an instance custom parameter in addition to the homonymous `xHeight` master property. In the case of the instance custom parameter, even though its value only contains decimal numbers, Glyphs.app stores it as a quoted string: that's because all the non-supported custom parameters' values are treated as strings; and in order to make it clear that their type is string and not integer or real, Glyphs.app quotes them when they look like a number. E.g.:

```
name = xHeight;
value = "530";
}
```

Actually, it's sufficient that such unsupported custom parameters values only _start with_ a digit for them to be wrapped in quotes. They are not quoted if they only comprise letters, or they contain digits but not in the start position.

```
{
name = all_letters_unquoted;
value = abc;
},
{
name = starts_with_digit_quoted;
value = "1abc";
},
{
name = contains_digit_unquoted;
value = abc1;
}
```

***

The types for the supported custom parameters appears to be registered in a plist file inside the Glyphs.app bundle:

/Applications/Glyphs.app/Contents/Frameworks/GlyphsCore.framework/Versions/A/Resources/customParameterTypes.plist

I assume that any custom parameter which is not listed there, will be implicitly treated as a string value by Glyphs.app.
For example, the above mentioned `xHeight` is not in there (as it's not actually a custom parameter but a property of masters).

However, I noticed some inconsistencies.

For example, the `weightClaass` instance custom parameter, which supposedly is among the supported ones (it shows up in the drop-down menu and is used extensively in the Noto fonts), is _not_ present in this list, even though for some reason the equivalent `openTypeOS2WeightClass` is present, and has the correct integer type. Because `weightClass` custom parameter doesn't have an explicit type assigned, it is stored as a quoted string, even if it really should be an integer:

```
{
name = weightClass;
value = "500";
}
```

Furthermore, the `codePageRanges` (and the equivalent `openTypeOS2CodePageRanges`) and the `panose` custom parameters (and maybe other similar ones) are simply marked as `array` type; but the plist does not specify what type the array _items_ should be; this may explain why `codePageRanges` or `panose` values are being treated as quoted strings even though one would expect them to be treated as intengers.

***

Similarly to the unsupported custom parameters, the values of the `userData` dictionary also seem to be stored as quoted strings when they start with , I guess following the same logic: i.e. unknown type, string type implied, starts with digits, thus wrap it in quotes.

```
userData = {
GSDimensionPlugin.Dimensions = {
"0A718E2F-231D-484E-9433-16A5230D2CE8" = {
HH = "158";
HV = "194";
OH = "158";
...
```

***

Finally, the `.appVersion` seems to be always treated as a string by Glyphs.app (quoted, since it usually starts with a digit); so we need to change our `glyphsLib.casting._TYPE_STRUCTURE` to treat `.appVersion` as a string instead of an integer.

**Comment by schriftgestalt** [comment]
I already fixed the `weightClass` and `codePageRanges` data types in version 2.5.

The userData tries to keep the data type of the values you put in. The `GSDimensionPlugin.Dimensions` are just strings that happen to look like numbers. But if you set the values from a script or open an .ufo and some of the font info is stored in the userData, the type should be kept.

**Comment by anthrotype** [comment]
I think this should be fixed now.
