### ISSUE TITLE
Implement glyphsLib.dump()

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#246]
Since one can load data using glyphsLib.load() it would be rather nice to have glyphsLib.save()

I guess implementing this would be the equivalent of competing in 10 back to back Ironmans.

**Comment by anthrotype** [comment]
we should call these `dump` and `dumps` like in the json module. 

behdad added them in a commit to master but I had to revert because of merge conflicts with classtree.

https://github.com/googlei18n/glyphsLib/commit/95e9c1c13025d7b68fbf6b3414a7877e6743aba0

we shall add these back and hook them to the new writer implementation.

**Comment by belluzj** [comment]
I will open a PR for that

**Comment by m4rc1e** [comment]
Thank you @belluzj you are a machine

**Comment by schriftgestalt** [comment]
Personally, I would move the loading/saving into the GSFont class like it is done in fonttools ‘font = TTFont(“path to file.ttf”)’.

**Comment by belluzj** [comment]
Actually it looks like there is already an API like you describe in GSFont

**Comment by schriftgestalt** [comment]
Yes. And thats why I would remove the load/save from the lib.
