### ISSUE TITLE
Master names

### ISSUE THREAD

**Issue by schriftgestalt** [googlei18n/glyphsLib#323]
https://github.com/googlei18n/glyphsLib/blob/092d2fc095cc85c4a99595c9f4441222ecc4b105/Lib/glyphsLib/classes.py#L1326

You should not deal with that here. The `.name` property is all you need. the old `.weight`
 and `.width` properties are only written to the file for compatibility reasons.

**Comment by belluzj** [comment]
OK, thanks for the comment. I thought that I had to match Glyphs' behaviour for two reasons:
1. when I tried this in Glyphs' UI, I think I remember that if I set a name that fits nicely into the weight/width, Glyphs will not write out the full name, only the weight/width, so glyphsLib will need to have some logic to piece back together a name from the weight/width anyway. Am I mistaken about that? Does Glyphs always writes out the full name of the master now?
2. I want to preserve the weight/width all the time because they are used to display the correct master icon in the toolbar at the top. Unless there is another way to do that?

**Comment by schriftgestalt** [comment]
1) I had it that the name was always written out. That would have caused a lot of noice in everybody files. So I disabled it again. 
2) the toolbar icon is not using the weight/width any more. That is an extra setting.

**Comment by anthrotype** [comment]
I think I've found a regression with regards to the generated UFO master names.

When building, e.g. `NotoSansTamil-MM.glyphs` from noto-source repo with fontmake and glyphsLib 2.2.1 (last stable release), I get things like "NotoSansTamil-CondensedLight.ufo" or "NotoSansTamil-CondensedBold.ufo", whereas with the latest master the width and weight components of the master names are swapped, and the weight appears first: e.g. "NotoSansTamil-LightCondensed.ufo"

I think this line is responsible for this:
https://github.com/googlei18n/glyphsLib/blob/5133a43a2c8652633935525f27c98059fdbc71a2/Lib/glyphsLib/classes.py#L1349-L1350

I'm not sure whether this was intentional. I'd prefer to keep the old behavior for backward compatibility. All noto sources rely on that convention (i.e. the width comes before the weight in the style name, e.g. "Condensed Light" instead of "Light Condensed").

**Comment by anthrotype** [comment]
applying this patch fixes it for me

```diff
diff --git a/Lib/glyphsLib/classes.py b/Lib/glyphsLib/classes.py
index 8e65f01..f263003 100755
--- a/Lib/glyphsLib/classes.py
+++ b/Lib/glyphsLib/classes.py
@@ -1347,7 +1347,7 @@ class GSFontMaster(GSBase):
             self.customParameters['Master Name'] = name
 
     def _joinName(self):
-        names = [self.weight, self.width, self.customName]
+        names = [self.width, self.weight, self.customName]
         names = [n for n in names if n]  # Remove None and empty string
         # Remove all occurences of 'Regular'
         while len(names) > 1 and "Regular" in names:
```

**Comment by moyogo** [comment]
@anthrotype Would it make sense to put customName first? For example when custom is optical size:  "{opticalSize} {width} {weight}".

**Comment by moyogo** [comment]
Or better, follow the order in `customParameter['Axes']` if defined.

**Comment by anthrotype** [comment]
we should probably do whatever glyphs.app does, while also try to reduce the amount of breaking. 
the MTI source files in noto-source repo reference the respective master by their postscript name, so "NotoSansTamil-LightCondensed" will raise a KeyError.

**Comment by anthrotype** [comment]
shall we keep this open or we're done here?

**Comment by belluzj** [comment]
I think we're done, until another regression is found. I think glyphsLib should keep the "split"/"join" logic until 2.5 is official and we can stop supporting 2.4 for real.
