### ISSUE TITLE
Changelog for next version

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/glyphsLib#351]
@belluzj could you help me draft this, at least the changes you made?
I’d like to make a release today.
Thanks

**Comment by belluzj** [comment]
Sorry, I had forgotten about this issue.

Changes since 2.2.1: https://github.com/googlei18n/glyphsLib/compare/v2.2.1...master

Added:
- `glyphsLib.to_glyphs(DesignSpaceDocument | list<defcon.Font>) -> GSFont` has been implemented and can create a Glyphs font from either a designspace document + source UFOs, or from a list of UFOs.
- `glyphsLib.to_designspace(GSFont) -> DesignSpaceDocument` can translate a Glyphs font into a designspace document and UFOs (reachable via `document.sources[i].font`)
- `to_ufos()`/`to_designspace()` (resp. `to_glyphs()`) have a new parameter `minimize_glyphs_diffs` (resp. `minimize_ufo_diffs`) which can be set to True when round-tripping. When true, glyphsLib stores more information in the produced file, in order to minimize diffs when coming back to the original file. It's interesting when using glyphsLib on files that are under version control.
- Handle custom axes and custom axis locations
- Handle Glyphs "annotations" (under a lib key in generated UFOs)
- Handle background images
- Handle smart components axes and values (but NOT outlines: there is no interpolation of smart components yet)
- Handle multiple unicode values per glyph
- Handle guidelines
- Handle Glyphs hints (under a lib key in generated UFOs)
- Handle Glyphs instances when using a designspace document
- Glyphs API methods
    - `GSFont.kerningForPair`, `GSFont.setKerningForPair`, `GSFont.removeKerningForPair`

Fixed:
- Don't crash on references to components that don't exist
- Parse various formats for multiple unicode values
- Parse custom data as base64 or hex-encoded bytes

Changed:
- The command line argument `-R`/`--no-round` is now `-r`/`--round-instances` and does the opposite
- The default names for the width and weight axes is now "Width" and "Weight" in generated designspace documents (@anthrotype did you make a comment about this change being a bad idea the other day?)

**Comment by anthrotype** [comment]
thanks jany!

> default names for the width and weight axes is now "Width" and "Weight" in generated designspace documents

that's ok, because we explicitly associate the named axes with their tag in the designspace dociument's `axes` element, and tools are expected to use these definitions when present. The internal axis name doesn't matter. And actually, being the same as the english labelname, lets us drop the latter as it's implicitly defined as the same as the axis name attribute.

**Comment by anthrotype** [comment]
> Parse custom data as base64 or hex-encoded bytes

I think we need to find a solution for this (see #354). I would like to only support hex and not base64 (as that was an unwanted deviation from the property list spec). However we need to do that properly, in a way that the parser and writer can roundrip themselves, and we don't end up writing textual strings as hex data, nor binary bytes as text.

**Comment by anthrotype** [comment]
> Handle Glyphs instances when using a designspace document

what do you mean here?

**Comment by belluzj** [comment]
> Handle Glyphs instances when using a designspace document
I thought that this was new but actually it was already present before, so you can remove the line. The only new thing is that they roundtrip.

**Comment by anthrotype** [comment]
https://github.com/googlei18n/glyphsLib/releases/tag/v2.3.0
