### ISSUE TITLE
Glyph data: glyph variants not properly categorized.

### ISSUE THREAD

**Issue by madig** [googlei18n/glyphsLib#386]
I stumbled over this bug: https://gitlab.gnome.org/GNOME/cantarell-fonts/issues/24. Inspecting the glyphsLib/fontmake generated binaries showed that several combining accents (in this case, dieresiscomb.case) had a non-zero advance width. Turns out that glyph variants are miscategorized:

```
In [1]: import glyphsLib

In [2]: glyphsLib.glyphdata.get_glyph("dieresiscomb")
Out[2]: Glyph(name='dieresiscomb', production_name='uni0308', unicode='̈', category='Mark', subCategory='Nonspacing')

In [3]: glyphsLib.glyphdata.get_glyph("dieresiscomb.case")
Out[3]: Glyph(name='dieresiscomb.case', production_name='dieresiscomb.case', unicode=None, category='Letter', subCategory=None)
```

**Comment by madig** [comment]
Glyphs.app:
```
print(Glyphs.glyphInfoForName("brevecomb").subCategory)
=> Nonspacing

print(Glyphs.glyphInfoForName("brevecomb.case").subCategory)
=> Nonspacing
```

**Comment by madig** [comment]
Apparently not that easy. Sigh.
```
Glyphs.glyphInfoForName("one_two.foo")
-> (u'Number', u'Ligature')
```

**Comment by madig** [comment]
Groan.
```
Glyphs.glyphInfoForName("a_parallel.circled").productionName or .name
=> uni00612225.circled

Glyphs.glyphInfoForName("a_Dboldscript-math").productionName or .name
=> a_Dboldscript-math
```
So uXXXXX glyphs are rejected and uniXXXX with a .suffix in the name get the suffix appended when I don't think they should.

**Comment by madig** [comment]
```
n=["a_a", "a_idotaccent", "a_brevecomb", "idotaccent_a", "idotaccent_brevecomb", "dieresiscomb", "dieresiscomb_a", "a_dieresiscomb"]

for name in n:
  i = Glyphs.glyphInfoForName(name)
  print(i.productionName or i.name)
```
```
a_a
a_i.loclTRK
uni00610306
i.loclTRK_a
idotaccent_brevecomb
uni0308
uni03080061
uni00610308
```
Uh...

**Comment by schriftgestalt** [comment]
What would be the preferred name for `a_Dboldscript-math`? `a_u1D4D3`?

The current implementation doesn't like ligatures with glyphs that have different script tags. I plan to change it to use the underscore syntax for the suffix too: `a-cy + Dboldscript-math` would become `a_Dboldscript-cy_math`. That looks a bit weird but it it needed because `a_Dboldscript-math` would could be decomposed into `a + Dboldscript-math` or `a-math + Dboldscript-math`.

The same will be used for the feature suffix. (this is mostly relevant for the automatic feature generation).

a.ss01 + b.ss01 > a_b.ss01 // if there is only suffix and no underscore, the suffix is applied to 
a.ss01 + b.ss02 > a_b.ss01_ss02
a + b.ss02 > a_b._ss02 // there is an empty suffix between the period and the underscore. 
a.ss01 + b > a_b.ss01_ 
a.ss01 + b + c > a_b_c.ss01_ equivalent to a_b_c.ss01__ (more then one underscores at the end can be omitted)

And should production names optimised for size? The name `idotaccent_brevecomb` could be shortened with a uni-name.

**Comment by madig** [comment]
> What would be the preferred name for a_Dboldscript-math? a_u1D4D3?

I'd think so, going from the AGL specification: https://github.com/adobe-type-tools/agl-specification#2-the-mapping

> a-cy + Dboldscript-math would become a_Dboldscript-cy_math.

Huh? I'd say it becomes `a-cy_Dboldscript-math`? The dash isn't used to separate anything and has no significance in the AGL lookup algorithm. Actually, since `a-cy` and `Dboldscript-math` are Glyph names and we want production names, it should be `uni0430_u1D4D3`, no?

> The same will be used for the feature suffix.

Not sure this is AGL-compliant. Or maybe it doesn't matter if a PDF reader will just strip everything after the first dot...

> And should production names optimised for size?

If I understand correctly, production names are only really relevant on the desktop, as an aid when broken PDF generators place glyph indices instead of Unicode text and the reader has to figure out which it's looking at. And font size doesn't matter on the desktop...
