### ISSUE TITLE
UFO to glyphs conversion

### ISSUE THREAD

**Issue by n8willis** [googlei18n/glyphsLib#74]
It would be extremely helpful for me to be able to convert UFO files directly to glyphs format. 

I realize from informal conversation that many of the internals necessary are in place or close; it wasn''t clear what remains.

I'm thinking primarily of the need to handle single UFOs, not multiple masters, although obviously that would be useful in the long run.

**Comment by schriftgestalt** [comment]
I started to implement a proper object model to represent glyphs files in memory. One advantage if it would be to able to write files. That is not 100% there yet and needs some updating an better integration with the rest of the code. 

And what is your usecase for this?

**Comment by n8willis** [comment]
The use case is working on collaborative projects between users using Glyphs and those using FontForge.  

(At least until I persuade you to release a Linux version of Glyphs, round-tripping through UFO is the best alternative.... :) )

**Comment by schriftgestalt** [comment]
it might be more useful to add .glyphs support to fontforge directly. 
The classes.py file from my branch in glyphsLib and the Fontlab export script can be used as reference. 
That would allow for better translation between values, e.g., you could keep the MM setup. 
I'm happy to help with the implementation.

**Comment by n8willis** [comment]
Well, personally, I'd consider a FontForge-only solution less useful; because there are other UFO-centric tools. @jamesgk , what do you think?

**Comment by jamesgk** [comment]
We have gotten requests for a UFO->Glyphs converter before. We can read UFOs into UFO-like Python objects and write Glyphs source from Glyphs-like Python objects but the missing piece is converting UFO-like objects to Glyphs-like objects. Basically the opposite of [builder.py](https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/builder.py) which is ~750 lines and pretty messy.

Complicating this as a todo item is that we also want to overhaul our Glyphs-like Python objects to be class-based instead of Python-builtin-based (as Georg mentioned; this could make builder.py cleaner as well as making glyphsLib more generally useful). That is kind of a few weeks out for me unfortunately since I have other obligations I have to get to. Perhaps in the meantime someone could write a rudimentary UFO obj -> Glyph obj converter based on what we have now.

**Comment by schriftgestalt** [comment]
Depending on the time pressure for the ufo>glyphs converter, I would wait until the object model is in better shape?

**Comment by adrientetar** [comment]
> a UFO -> Glyphs converter is yet to be built.

But if you want a glyphs file you probably have the Glyphs app too. Is its import function dissactisfactory or anything?

**Comment by jamesgk** [comment]
> But if you want a glyphs file you probably have the Glyphs app too

Not necessarily. The use-case here and with Noto is that someone may want to contribute to a project which is based on existing Glyphs sources, but without using the Glyphs app.

**Comment by adrientetar** [comment]
Oh I see.

**Comment by schriftgestalt** [comment]
My (old) branch is able to write .glyphs file. So if we could implement this, it would be much easier to implement moving data in both directions.

**Comment by jamesgk** [comment]
> My (old) branch is able to write .glyphs file.

So is the master branch. The missing piece is converting UFO-structured data to Glyphs-structured data.

> So if we could implement this, it would be much easier to implement moving data in both directions.

Assuming you're talking about overhauling the Glyphs data handling, that's a big if. It's not a trivial task, and I'm quite busy these days. Honestly at this point I'm not sure if I'm ever going to have time for it. But I would like to see it happen.

**Comment by schriftgestalt** [comment]
There was a plan to refactor the lib to be object oriented. Then it would be easier to such things as migrating data.

**Comment by jamesgk** [comment]
Yes, that's exactly what I was referring to as "overhauling the Glyphs data handling".

**Comment by belluzj** [comment]
Fixed in #244

**Comment by anthrotype** [comment]
🍰
