### ISSUE TITLE
Record commit hash of GlyphData?

### ISSUE THREAD

**Issue by brawer** [googlei18n/glyphsLib#93]
In the review of https://github.com/googlei18n/glyphsLib/pull/92, @anthrotype asked if the `glyphdata_generated.py` file should record the commit hash of the `schriftgestalt/GlyphsInfo` repository from which the GlyphData.xml was downloaded. One option is to add `schriftgestalt/GlyphsInfo` repo as a git submodule of `glyphsLib`, and run the `generate_glyphdata.py` script from the local submodule checkout, instead of curl-ing the file from `raw.githubusercontent.com` as it does now.

Thoughts?

**Comment by anthrotype** [comment]
Another way, instead of the submodule, would be to use send a `GET` request to Github API and retrieve the commit hash of `schriftgestalt/GlyphsInfo/master`:

https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

A bit of curl and sed does the trick:
```bash
curl https://api.github.com/repos/schriftgestalt/GlyphsInfo/commits/master --stderr /dev/null | grep '"sha":' | head -n1 | sed -E 's/  "sha": "(.*)",/\1/'
```

I'm sure with `urllib.request` you can do the from Python:
https://docs.python.org/3/library/urllib.request.html#module-urllib.request
